language: c

# The interpreter's build doesn't need any depth.
git:
  depth: 1

# Ignore the warnings about an initial job.
# All jobs go into jobs.

# These are for the ancillary jobs.
jobs:
  include:
    - os: linux
      arch: amd64
      env:
        - MATRIX_EVAL=""

    - os: linux
      arch: amd64
      compiler: clang
      env:
        - MATRIX_EVAL=""

    - os: linux
      arch: arm64
      env:
        - MATRIX_EVAL=""

    - os: linux
      arch: ppc64le
      env:
        - MATRIX_EVAL=""

    - os: linux
      arch: s390x
      env:
        - MATRIX_EVAL=""

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL=""

before_install:
 - eval "${MATRIX_EVAL}"

script:
 - cmake . -DCMAKE_BUILD_TYPE=RELEASE -DWITH_COVERAGE=on || exit 1
 - cmake --build . -- -j2 || exit 1
 - ./pre-commit-tests || exit 1
